trigger:
  branches:
    include:
      - main
      - development

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'



    steps:

      - task: SonarCloudPrepare@4
        inputs:
          SonarCloud: 'Devops'
          organization: 'x00201548'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: 'x00201548_CA3DevOps'
          cliProjectName: 'CA3DevOps'
          cliSources: 'app'
          extraProperties: |
            sonar.python.coverage.reportPaths=coverage.xml
            sonar.python.xunit.reportPath=junit.xml
        displayName: 'SonarCloud'

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
      

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install Dependencies'

      - script: pylint app/*.py || true
        displayName: 'Static Analysis with Pylint'

      - script: |
          pytest -q --cov=app/calc.py --cov-report=xml --cov-fail-under=80 --junitxml=junit.xml
        displayName: 'Run Tests with Coverage (fail <80%)'

      - task: SonarCloudAnalyze@4
        displayName: 'Analyze'
      - task: PublishCodeCoverageResults@2
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: 'coverage.xml'
          reportDirectory: '.'
        displayName: 'Publish Coverage'

      - task: CopyFiles@2
        inputs:
          contents: |
            app/**
            requirements.txt
            *.py
          targetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Copy Application Files'


      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'drop'

- stage: DeployDev
  displayName: "Deploy To Dev"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployDev
    environment: 'Dev'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - script: echo "Deploying to Dev environment"
            displayName: 'Deploy to Dev'

- stage: DeployProduction
  displayName: "Deploy To Production"
  dependsOn: DeployDev
  condition: succeeded()
  jobs:
  - deployment: DeployProduction
    environment: 'Production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - script: echo "Deploying to Production environment"
            displayName: 'Deploy to Production'
